#!/bin/bash

if [[ -e ~/.gazebo/models ]]
then
	echo "models Directory exists."
	rm -rf ~/.gazebo/models/rom2109*
else
	mkdir ~/.gazebo/models
fi
cp -r ./models/* ~/.gazebo/models
echo "models Copy finished!"
